### ISSUE TITLE
Crashes on login on Linux

### ISSUE THREAD

**Issue by dnaf** [EionRobb/purple-discord#18]
Sorry if I'm doing something wrong!

Pidgin crashes after I log in and enter my mobile authenticator code with the following message in the terminal

```
(Pidgin:29559): Json-CRITICAL **: json_object_get_string_member: assertion 'JSON_NODE_HOLDS_VALUE (node) || JSON_NODE_HOLDS_NULL (node)' failed

(Pidgin:29559): Json-CRITICAL **: json_object_get_string_member: assertion 'JSON_NODE_HOLDS_VALUE (node) || JSON_NODE_HOLDS_NULL (node)' failed
Pidgin 2.12.0 has segfaulted and attempted to dump a core file.
```

Here's the backtrace from `gdb`

```
Python Exception <class 'gdb.error'> There is no member named keys.: 
#0  0x00007ffff492ca14 in free () at /usr/lib/libc.so.6
#1  0x00007fffe4b9d88f in discord_process_dispatch (data=<optimized out>, type=<optimized out>, da=0xbe7330) at libdiscord.c:1116
        members = <optimized out>
        flags = <optimized out>
        presences = <optimized out>
        guild_id = <optimized out>
        users = 0x7d7930 = {0x3, 0x0}
        l = <optimized out>
        j = <optimized out>
        user_list = 0xebbf00
        type = <optimized out>
        seq = <optimized out>
        parser = <optimized out>
        root = <optimized out>
        obj = <optimized out>
        opcode = <optimized out>
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#2  0x00007fffe4b9d88f in discord_process_frame (frame=<optimized out>, da=0xbe7330) at libdiscord.c:1764
        type = <optimized out>
        seq = <optimized out>
        parser = <optimized out>
        root = <optimized out>
        obj = <optimized out>
        opcode = <optimized out>
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#3  0x00007fffe4b9d88f in discord_socket_got_data (userdata=0xbe7330, conn=<optimized out>, cond=<optimized out>)
    at libdiscord.c:1999
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#4  0x000000000046965e in  ()
#5  0x00007ffff551166a in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5511a20 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5511d42 in g_main_loop_run ()
    at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff67d73a7 in gtk_main ()
    at /usr/lib/libgtk-x11-2.0.so.0
#9  0x0000000000431e99 in main ()
(gdb) bt full
Python Exception <class 'gdb.error'> There is no member named keys.: 
#0  0x00007ffff492ca14 in free () at /usr/lib/libc.so.6
#1  0x00007fffe4b9d88f in discord_process_dispatch (data=<optimized out>, type=<optimized out>, da=0xbe7330) at libdiscord.c:1116
        members = <optimized out>
        flags = <optimized out>
        presences = <optimized out>
        guild_id = <optimized out>
        users = 0x7d7930 = {0x3, 0x0}
        l = <optimized out>
        j = <optimized out>
        user_list = 0xebbf00
        type = <optimized out>
        seq = <optimized out>
        parser = <optimized out>
        root = <optimized out>
        obj = <optimized out>
        opcode = <optimized out>
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#2  0x00007fffe4b9d88f in discord_process_frame (frame=<optimized out>, da=0xbe7330) at libdiscord.c:1764
        type = <optimized out>
        seq = <optimized out>
        parser = <optimized out>
        root = <optimized out>
        obj = <optimized out>
        opcode = <optimized out>
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#3  0x00007fffe4b9d88f in discord_socket_got_data (userdata=0xbe7330, conn=<optimized out>, cond=<optimized out>) at libdiscord.c:1999
        ya = 0xbe7330
        length_code = 0 '\000'
        read_len = <optimized out>
        done_some_reads = 1
#4  0x000000000046965e in  ()
#5  0x00007ffff551166a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5511a20 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5511d42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff67d73a7 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#9  0x0000000000431e99 in main ()
```

**Comment by EionRobb** [comment]
Oh, actually, I think I see the problem

**Comment by EionRobb** [comment]
Can you try with that commit?

**Comment by dnaf** [comment]
Seems to work fine! Thanks for the extremely fast fix ^-^

**Comment by EionRobb** [comment]
Yay \o/  Thanks for the fast testing :)
