### ISSUE TITLE
Cannot log in from remote server via Finch

### ISSUE THREAD

**Issue by vladkorotnev** [EionRobb/purple-discord#243]
Finch refuses to enable the account with a "Bad Password" error. 
Apparently this is due to logging in from a different GeoIP zone than usual. 
However no email is being sent to confirm the login attempt.
Is there any workaround for this not involving remote X and a web browser?

**Comment by EionRobb** [comment]
Hmm.... does the debug log show whether it's asking for a captcha, or is it straight up blocking you?

**Comment by EionRobb** [comment]
Actually, that was a dumb thought... how would Finch display a captcha image.

**Comment by vladkorotnev** [comment]
Sure, how do I get the debug log from it?

**Comment by EionRobb** [comment]
`finch -d  2> ~/debug.log` maybe hopefully

**Comment by vladkorotnev** [comment]
Looks like a captcha indeed.

```
(10:52:48) network: NetworkManager not active. Assuming connection exists.
(10:52:52) account: Connecting to account XXXXXXXXXXXXXXX.
(10:52:52) connection: Connecting. gc = 0x55d2696e60c0
(10:52:52) discord: Fetching url https://discordapp.com/api/v6/auth/login
(10:52:52) discord: With postdata ###PASSWORD REMOVED###
(10:52:52) util: requesting to fetch a URL
(10:52:52) dnsquery: Performing DNS lookup for discordapp.com
(10:52:52) signals: Signal data for chat-conversation-typing not found!
(10:52:52) dns: Created new DNS child 25342, there are now 1 children.
(10:52:52) dns: Successfully sent DNS request to child 25342
(10:52:52) dns: Got response for 'discordapp.com'
(10:52:52) dnsquery: IP resolved for discordapp.com
(10:52:52) proxy: Attempting connection to 104.16.59.5
(10:52:52) proxy: Connecting to discordapp.com:443 with no proxy
(10:52:52) proxy: Connection in progress
(10:52:52) proxy: Connecting to discordapp.com:443.
(10:52:52) proxy: Connected to discordapp.com:443.
(10:52:52) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(10:52:52) nss: subject=CN=discordapp.com,OU=PositiveSSL,OU=Domain Control Validated issuer=CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
(10:52:52) nss: subject=CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB issuer=CN=COMODO RSA Certification Authority,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
(10:52:52) nss: subject=CN=COMODO RSA Certification Authority,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB issuer=CN=AddTrust External CA Root,OU=AddTrust External TTP Network,O=AddTrust AB,C=SE
(10:52:52) nss: partial certificate chain
(10:52:52) certificate/x509/tls_cached: Starting verify for discordapp.com
(10:52:52) certificate/x509/tls_cached: Checking for cached cert...
(10:52:52) certificate/x509/tls_cached: ...Found cached cert
(10:52:52) nss/x509: Loading certificate from /home/x/.purple/certificates/x509/tls_peers/discordapp.com
(10:52:52) certificate/x509/tls_cached: Peer cert matched cached
(10:52:52) nss/x509: Exporting certificate to /home/x/.purple/certificates/x509/tls_peers/discordapp.com
(10:52:52) util: Writing file /home/x/.purple/certificates/x509/tls_peers/discordapp.com
(10:52:52) nss: Trusting CN=discordapp.com,OU=PositiveSSL,OU=Domain Control Validated
(10:52:52) certificate: Successfully verified certificate for discordapp.com
(10:52:52) util: request constructed
(10:52:53) util: Response headers: 'HTTP/1.1 400 BAD REQUEST
Date: Thu, 30 May 2019 05:52:53 GMT
Content-Type: application/json
Content-Length: 37
Connection: close
Set-Cookie: __cfduid=d172db873b29d918541b7ea8bd5c2f71a1559195572; expires=Fri, 29-May-20 05:52:52 GMT; path=/; domain=.discordapp.com; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Via: 1.1 google
Alt-Svc: clear
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4dee71cacb898e89-DME

'
(10:52:53) util: parsed 37
(10:52:53) discord: Got response: {"captcha_key": ["captcha-required"]}
(10:52:53) connection: Connection error on 0x55d2696e60c0 (reason: 2 description: Bad username/password)
(10:52:53) account: Disconnecting account XXXXXXXXXXXXX (0x55d26923e9f0)
(10:52:53) connection: Disconnecting connection 0x55d2696e60c0
(10:52:53) connection: Destroying connection 0x55d2696e60c0

```

**Comment by EionRobb** [comment]
Have you tried using https://github.com/nickolas360/harmony to login?

**Comment by vladkorotnev** [comment]
Just tried and got this

```
Press enter to start the challenge...


Error encountered while solving the CAPTCHA:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/harmony/harmony.py", line 295, in get_captcha_key
    gui=librecaptcha.has_gui(), debug=self.debug,
  File "/usr/local/lib/python3.5/dist-packages/librecaptcha/librecaptcha.py", line 39, in has_gui
    from . import gui  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/librecaptcha/gui.py", line 340
    self.gui: "Gui" = gui
            ^
SyntaxError: invalid syntax

```

**Comment by EionRobb** [comment]
I just added some instructions to the Readme to be able to grab your auth token from the browser.  Can you try using them to add the token to ~/.purple/accounts.xml (while Finch is closed) and see if that works?

**Comment by vladkorotnev** [comment]
The instructions weren't really clear (I tried adding a new `<token>` entry initially) but when I got it right it worked! Thanks a lot!
