### ISSUE TITLE
Segmentation fault: hash_table=<error reading variable: Cannot access memory at address 0x79>0x41

### ISSUE THREAD

**Issue by bodqhrohro** [EionRobb/purple-discord#305]
```
#0  g_hash_table_iter_init (iter=0x7fffffffacf0, hash_table=<error reading variable: Cannot access memory at address 0x79>0x41)
    at ../../../glib/ghash.c:1125
#1  0x00007ffff0e9fbe5 in  () at /usr/lib/purple-2/libdiscord.so
#2  0x00007ffff0ea1247 in  () at /usr/lib/purple-2/libdiscord.so
#3  0x00005555555cb1e2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x555558f84820) at ././pidgin/gtkeventloop.c:73
#4  0x00007ffff72864de in g_main_dispatch (context=0x555555684800) at ../../../glib/gmain.c:3309
#5  g_main_context_dispatch (context=context@entry=0x555555684800) at ../../../glib/gmain.c:3974
#6  0x00007ffff7286890 in g_main_context_iterate
    (context=context@entry=0x555555684800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
#7  0x00007ffff728691f in g_main_context_iteration (context=0x555555684800, may_block=1) at ../../../glib/gmain.c:4108
#8  0x00007ffff7762361 in gtk_main_iteration () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x00007ffff16da655 in conversation_created_cb (conv=<optimized out>) at plugin.c:91
#10 0x00007ffff7186fdc in purple_signal_emit_vargs
    (instance=<optimized out>, signal=0x55555562297a "conversation-switched", args=args@entry=0x7fffffffaf50) at ././libpurple/signals.c:482
#11 0x00007ffff718713e in purple_signal_emit (instance=<optimized out>, signal=<optimized out>) at ././libpurple/signals.c:434
#15 0x00007ffff738fedf in <emit signal ??? on instance 0x555555d208d0 [GtkNotebook]>
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
    #12 0x00007ffff7370fd2 in g_closure_invoke
    (closure=0x555556660d40, return_value=0x0, n_param_values=3, param_values=0x7fffffffb1f0, invocation_hint=0x7fffffffb170)
@--Type <RET> for more, q to quit, c to continue without paging--
    at ../../../gobject/gclosure.c:810
    #13 0x00007ffff73841b3 in signal_emit_unlocked_R
    (node=node@entry=0x55555574c020, detail=detail@entry=0, instance=instance@entry=0x555555d208d0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffb1f0) at ../../../gobject/gsignal.c:3812
    #14 0x00007ffff738f54f in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffb3d0)
    at ../../../gobject/gsignal.c:3498
#16 0x00007ffff77856db in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#17 0x00007ffff7764a8b in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#21 0x00007ffff738fedf in <emit signal ??? on instance 0x555555d208d0 [GtkNotebook]>
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3554
    #18 0x00007ffff7370fd2 in g_closure_invoke
    (closure=0x5555556e1e60, return_value=0x7fffffffb6a0, n_param_values=2, param_values=0x7fffffffb700, invocation_hint=0x7fffffffb680)
    at ../../../gobject/gclosure.c:810
    #19 0x00007ffff7383f06 in signal_emit_unlocked_R
    (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x555555d208d0, emission_return=emission_return@entry=0x7fffffffb820, instance_and_params=instance_and_params@entry=0x7fffffffb700) at ../../../gobject/gsignal.c:3780
    #20 0x00007ffff738f078 in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffb8d0)
@--Type <RET> for more, q to quit, c to continue without paging--
    at ../../../gobject/gsignal.c:3508
#22 0x00007ffff787c9e4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#23 0x00007ffff7762cbc in gtk_propagate_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00007ffff77630b3 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#25 0x00007ffff75d510c in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#26 0x00007ffff728660d in g_main_dispatch (context=0x555555684800) at ../../../glib/gmain.c:3309
#27 g_main_context_dispatch (context=context@entry=0x555555684800) at ../../../glib/gmain.c:3974
#28 0x00007ffff7286890 in g_main_context_iterate (context=0x555555684800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4047
#29 0x00007ffff7286b63 in g_main_loop_run (loop=0x5555574d7ae0) at ../../../glib/gmain.c:4241
#30 0x00007ffff776212a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#31 0x0000555555590970 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:939
```
I recently joined the Rust Discord server, and noticed that purple-discord started occasionally popping out some channels, even though it seemed to do this before only for channels where I (or @all) was mentioned. May be related, but may be an allocation failure as well, as this crash happened when the system was under heavy load.

**Comment by EionRobb** [comment]
Can you rebuild the libdiscord.so with debug symbols? Right not its not clear where the crash is happening, only that its happening in the discord plugin

**Comment by bodqhrohro** [comment]
Done; hopefully it will be reproduced again.
