### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mimi89999** [EionRobb/purple-discord#33]
After some time, without me doing anything, Pidgin with purple-discord crashes. Here it the backtrace:

```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
discord_process_dispatch (da=da@entry=0x555556932040, type=type@entry=0x555556aeffe0 "GUILD_SYNC", data=data@entry=0x555556e0e020)
    at libdiscord.c:1582
1582				g_array_append_val(guild->members, u->id);
(gdb) bt full
#0  discord_process_dispatch (da=da@entry=0x555556932040, type=type@entry=0x555556aeffe0 "GUILD_SYNC", data=data@entry=0x555556e0e020)
    at libdiscord.c:1582
        member = 0x555556cbaf60
        u = 0x555556a7a510
        roles = <optimized out>
        user = <optimized out>
        j = 20
        members = <optimized out>
        guild_id = <optimized out>
        gid = 257967589123293184
        users = 0x0
        flags = 0x0
        iter = {dummy1 = 0x555556dc0060, dummy2 = 0x7ffff55131a0 <g_hash_table_lookup+176>, dummy3 = 0x6, dummy4 = -418843166, 
          dummy5 = 32767, dummy6 = 0x7ffff556a610}
        key = 0x555556dc00a0
        value = 0x1
        user_list = 0x5555559f41e0
        presences = 0x555556e0e0e0
        guild = 0x0
#1  0x00007fffe708c798 in discord_process_frame (frame=<optimized out>, da=0x555556932040) at libdiscord.c:2241
        type = <optimized out>
        seq = <optimized out>
        parser = 0x555556dc00a0
        root = <optimized out>
        obj = <optimized out>
        opcode = <optimized out>
#2  discord_socket_got_data (userdata=0x555556932040, conn=0x555556932730, cond=<optimized out>) at libdiscord.c:2478
        ya = 0x555556932040
        length_code = 39 '\''
        read_len = <optimized out>
        done_some_reads = 1
#3  0x00005555555c5bde in ?? ()
No symbol table info available.
#4  0x00007ffff55246aa in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff5524a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff5524d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ffff67ce3b7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#8  0x000055555558c322 in main ()
No symbol table info available.
```

**Comment by p4plus2** [comment]
Do you know if your internet dropped or if discord happened to disconnect near when this happened?  I'm starting some testing now, I'll see if I can replicate and patch this up.

**Comment by mimi89999** [comment]
@p4plus2 My Internet is stable... I don't know if Discord disconnected...

**Comment by p4plus2** [comment]
I still haven't replicated the crash yet, I don't suppose you've come across any additional details for replication?  I'll keep searching.

**Comment by mimi89999** [comment]
Tell me where I can add logging to help you...

**Comment by p4plus2** [comment]
Pushed an attempted fix, its a bit of a blind patch though.  Lets see if this helps you out any.

**Comment by mimi89999** [comment]
1. I am also connected to Discord from the browser on the same computer (didn't try without... I will do that tomorrow)

2. The crash happens when I am not interacting with Discord. When I make a break or code and other people behave normally (what one would expect to happen in most rooms). Because of that, I don't know when exactly it crashes... I check gdb once and Pidgin is still running, I check it later and I see the crash...

**Comment by mimi89999** [comment]
I can only check your patch in 8h...

**Comment by mimi89999** [comment]
@p4plus2 I left Pidgin running for several hours and it didn't crash, so I am closing that issue...
